name: merged_app
description: A new Flutter project that merges a Crypto app and a News app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # من تطبيق العملات الرقمية (Crypto)
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2  # إضافة حزمة bloc الأساسية
  equatable: ^2.0.5
  http: ^1.1.0
  dio: ^5.3.2
  intl: ^0.18.1

  # من تطبيق الأخبار (News)
  get_it: ^7.6.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true